### ISSUE TITLE
Importing pdos lists created with cp2k 

### ISSUE THREAD

**Issue by Scemp** [aim2dat/aim2dat#75]
At the moment, if you want to import `pdos` for `cp2k`, you only have the opportunity to import it for each element. If you modify the input `LDOS` from cp2k to sum certain atoms, you can not import these lists yet. This is imported in the following line:

https://github.com/aim2dat/aim2dat/blob/eae8d8f4f2045f9b74332295f848a0f366d17dc3/aim2dat/io/cp2k/bands_dos.py#L70

I would suggest changing it to:

```suggestion
@read_multiple(r".*-?(?P<spin>[A-Z]+)?_?(list)(k)?.*\.pdos$")
```
Therefore, the user can also import these modified lists.

**Comment by hdsassnick** [comment]
That is a good point. I am not very familiar with the CP2K naming scheme.

We should have a regex identifier that works with all kinds of pdos output formats.

@scemp, if you have some spare time, please feel free to go ahead and create a PR. Ideally, we should also test the different naming schemes. Otherwise, I am also happy to fix the issue somewhere around the end of this month or beginning of the next one.
